version: "3.7"
volumes:
  kopring-webflux-dbdata:
services:
  kitchen-force-db:
    image: mysql:8.0
    restart: unless-stopped
    container_name: kopring-db
    ports:
      - "13009:3306"
    environment:
      - MYSQL_DATABASE=kopring
      - MYSQL_USER=kopring
      - MYSQL_PASSWORD=ko1234
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - kopring-webflux-dbdata:/var/lib/mysql8